startup_session test

# Enable MacOS style word jumping
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# Turn on shell integration - see kitty docs
shell_integration enabled

# Window navigation
# Use https://github.com/knubie/vim-kitty-navigator to support vim-like keybinds
map ctrl+j kitten pass_keys.py bottom ctrl+j "^.*nvim$"
map ctrl+k kitten pass_keys.py top    ctrl+k "^.*nvim$"
map ctrl+h kitten pass_keys.py left   ctrl+h "^.*nvim$"
map ctrl+l kitten pass_keys.py right  ctrl+l "^.*nvim$"

# Open windows in CWD
map kitty_mod+t new_tab_with_cwd
map kitty_mod+enter new_window_with_cwd

# Toggle Fullscreen
map cmd+f toggle_fullscreen

allow_remote_control yes
listen_on unix:/tmp/mykitty
